"""empty message

Revision ID: c19a21698de5
Revises: a5cffa318ac2
Create Date: 2024-10-14 22:10:29.599980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19a21698de5'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personajes',
    sa.Column('Id_Personajes', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=250), nullable=False),
    sa.Column('Birthline', sa.Integer(), nullable=False),
    sa.Column('Gender', sa.String(length=250), nullable=False),
    sa.Column('Height', sa.Integer(), nullable=False),
    sa.Column('Skin_color', sa.String(length=250), nullable=False),
    sa.Column('Eye_color', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('Id_Personajes')
    )
    op.create_table('planetas',
    sa.Column('ID_Planeta', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=250), nullable=False),
    sa.Column('Rotation_Period', sa.Integer(), nullable=False),
    sa.Column('Orbital_Period', sa.Integer(), nullable=False),
    sa.Column('Gravity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ID_Planeta')
    )
    op.create_table('usuario',
    sa.Column('ID_Usuario', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=250), nullable=False),
    sa.Column('Apellido', sa.String(length=250), nullable=False),
    sa.Column('Correo', sa.String(length=250), nullable=False),
    sa.Column('Password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('ID_Usuario')
    )
    op.create_table('datos__favoritos',
    sa.Column('id_Favoritos', sa.Integer(), nullable=False),
    sa.Column('user_Id', sa.Integer(), nullable=True),
    sa.Column('Planeta_ID', sa.Integer(), nullable=True),
    sa.Column('Personajes_Id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Personajes_Id'], ['personajes.Id_Personajes'], ),
    sa.ForeignKeyConstraint(['Planeta_ID'], ['planetas.ID_Planeta'], ),
    sa.ForeignKeyConstraint(['user_Id'], ['usuario.ID_Usuario'], ),
    sa.PrimaryKeyConstraint('id_Favoritos')
    )
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('email', name='user_email_key')
    )
    op.drop_table('datos__favoritos')
    op.drop_table('usuario')
    op.drop_table('planetas')
    op.drop_table('personajes')
    # ### end Alembic commands ###
